export const LOCATIONS = [
  "Aakor St",
  "Abua Street",
  "Agah community",
  "Agburu Street",
  "Agip Gas Plant Road",
  "Agip Rd",
  "Ajua St",
  "Akabuka community",
  "Akoritha Street",
  "Akputa Waterside",
  "Alinso-Okenu",
  "Amah community",
  "Asa Okoromah Street",
  "Atasia St",

  "Cemetrey Road",
  "Chief Matthew Mbur Rd",
  "Church Rd",
  "Court Road",
  "Creek Rd",

  "Dakoru St",
  "Dan Lane",
  "Dan St",
  "Dr Innocent Mazi Street",

  "Eboaha",
  "Ebocha Road",
  "Ede community",
  "Egbada community",
  "Egbada Road",
  "Egbema community",
  "Egbema Street",
  "Egita-Akabuta community",
  "Ekpe-Aggah community",
  "Ekpe-Mgbede community",
  "Elehia community",
  "Elieta community",
  "Emmanuel Enyadike Street",
  "Erema community",
  "Erema Street",
  "Eze Jukwu Road",
  "Eze Ohali Street",
  "Eze Onwusah Street",
  "Ezekiel Olowu Street",

  "Gc Okoromah",

  "I O Osianye Rd",
  "Ibewa community",
  "Ichoku Street",
  "Ifeanyi Nkwo St",
  "Ihiukwu Street",
  "Ikiri community",
  "Ikiri Road",
  "Itu community",
  "Iyasara Street",

  "Justtypee St",

  "Kreigani community",
  "Kreigani Road",

  "Location Road",

  "Market Road",
  "Mgbede community",

  "Ndoni community",
  "Ndoni St",
  "Nwagbogwe St",

  "Oba Rd",
  "Obagi community",
  "Obiebie community",
  "Obigbo community",
  "Obiozumini / Obukegi community",
  "Obite community",
  "Oboburu Street",
  "Oboburu community",
  "Obohia Road",
  "Obor community",
  "Obor Road",
  "Obosi St",
  "Obrikom community",
  "Obrikom Rd",
  "Oburuwahor Street",
  "Ochoma Street",
  "Ogaranya Ewo Street",
  "Ogbidi community",
  "Ogbogu community",
  "Ogbowu St",
  "Ogbu Ukwu Street",
  "Ogolo Street",
  "Ohali-Elu community",
  "Ohali-Usomini community",
  "Ohiauga community",
  "Okansu community",
  "Okposi 1 community",
  "Okposi 2 community",
  "Okpurukpuali community",
  "Okwuzu community",
  "Osiakpu community",
  "Osakwe St",
  "Osere Nweze St",
  "Osere Street",

  "Palace Rd",
  "Park Avenue",
  "Police Rd",

  "SO Omasi Street",
  "Star Point Road",

  "Tourist Rd",

  "Ubeta-Obido Rd",
  "Uche Osaigo Street",
  "Ugo Ozi Street",
  "Uju community",
  "Ukpazi community",
  "Umu Chikere Road",
  "Umu Enyike Rd",
  "Umu Nkara Street",
  "Umu Obah Street",
  "Umu Ohali Street",
  "Umu Oyiro street",
  "Uriem Street",

  "Victor Masi Street",
  "Vos Amoke Cl"
];
